### PR TITLE
Fix filesystem credentials dialog

### LINKED ISSUE #100: Update FTP credentials form design
Current designs:

ftp-credentials_720
ftp-credentials-with-ssh_720

These could use with just a little bit of tweaking to improve hierarchy and spacing. I'll work on that a bit and then post up some designs here.

### LINKED ISSUE #121: Single plugin update does not work on updates page
I've updated a plugin.

As you can see in the screenshot, after plugin is updated, still say updating.

Aggiornato! means updated
Aggiornamento in corso... means updating...

I'm using chrome 51.0.2704.47 beta (64-bit) on mac.
aggiornamenti_di_wordpress_ _wolly_s_weblog_ _wordpress

### PR DESCRIPTION
**Pull request by swissspidy**
After https://core.trac.wordpress.org/changeset/37467, the dialog didn't work properly anymore.

Any updates to the HTML in the dialog need to be changed in core directly, as the dialog code can't be filtered.

Fixes #121 and #170.
See also #100, #122.

### CODE REVIEW

**Comment by swissspidy** [comment]
See https://github.com/obenland/shiny-updates/issues/122#issuecomment-222386734 for what's left open here.

**Comment by swissspidy** [comment]
@obenland Is this one ready?

**Comment by obenland** [comment]
Nope, still working on it.

**Comment by obenland** [comment]
Ready for your review/test/merge.

**Comment by obenland** [comment]
@swissspidy I updated the callback business. *Now* it's ready for your review/test/merge.

**Pull request merged**
