### PR TITLE
Shiny installs on the import screen

### LINKED ISSUE #148: Install from the Tools - Import screen
Trying to install an Importer Plugin from the Tools > Import screen currently fails.
- click on an importer
- the plugin details modal opens
- when the modal content has finished loading, Chrome console displays an error `SyntaxError: Unexpected token o in JSON at position 1`
- clicking on the "Install Now" button in the modal does nothing

### PR DESCRIPTION
**Pull request by swissspidy**
Let's fix the flow when installing importers.

Fixes #148.

***work in progress***

### CODE REVIEW

**Comment by obenland** [comment]
The only thing missing is a spinner during installation to suggest activity. The table is not really made for a spinner like that unless we append it somewhere. Prepending it would be pretty jarring. Not sure what the best way would be. @mapk maybe?

**Comment by mapk** [comment]
So after I installed the Blogger importer, I got the Success notification - yay!
I thought I'd click the Blogger importer in the list again to see what happens...

screen shot 2016-06-01 at 11 30 31 am

Yo, dawg, we heard you like WordPress, so we put WordPress in your WordPress. :)

**Comment by obenland** [comment]
Thanks @mapk, fixed.

**Comment by mapk** [comment]
> The only thing missing is a spinner during installation to suggest activity.

Would the spinner just go in the "Install Now" button on the modal?

**Comment by obenland** [comment]
The modal closes itself after the button was clicked.

**Comment by mapk** [comment]
I was trying to click the "Install Now" button and then try to click the importer link in the table again real fast before it installed to see what would happen. I'm not sure if I did it in time, but I got this message.

screen shot 2016-06-01 at 12 50 30 pm


Anyways, in regards to adding a spinner next to the line item in the table, I agree it might be jarring, but that jarring action might be what's needed to alert the user that something's happening. It could be the very thing that draws their attention.

**Comment by obenland** [comment]
That looks like it's a bug in the Blogroll importer. I couldn't reproduce it with any other importer and it also occurs with Shiny Updates disabled.

**Comment by swissspidy** [comment]
> The only thing missing is a spinner during installation to suggest activity. The table is not really made for a spinner like that unless we append it somewhere.

Maybe it's time to give that table a little refresh to make it possible to add a spinner and to make it look more like other tables in WordPress.

**Comment by obenland** [comment]
Or we'll append a spinner to the plugin name?

**Comment by mapk** [comment]
I was thinking just add the spinner before the plugin name in the table. 

If we revamp the table, are we going to need a plugin icon for each? Do they have icons?

**Comment by swissspidy** [comment]
Okay, let's add a spinner before the plugin name for now and leave the table layout revamp to the ticket you mentioned. I have some ideas and will comment there.

**Comment by obenland** [comment]
@swissspidy: Ready for review/test/merge at your convenience.

**Comment by swissspidy** [comment]
Works like a charm so far. Only weird thing I noticed was that activation doesn't seem to work.

To reproduce:

1. Install importer
2. Click on "Activate plugin & run importer link"
3. Get an error saying that there was unexpected output during activation. That output looks like this:  
  
  ```
 Fatal error: Cannot redeclare blogger_importer_init() (previously declared in /srv/www/wordpress-develop/src/wp-content/plugins/blogger-importer/blogger-importer.php:904) in /srv/www/wordpress-develop/src/wp-content/plugins/blogger-importer/blogger-importer.php on line 904
```
4. Now on the plugins page, click "Activate" again and everything works fine.

**Comment by swissspidy** [comment]
Strange, happens without Shiny Updates as well. Assume it's a bug on my end, otherwise I'll open a trac ticket.

**Comment by obenland** [comment]
FWIW, most importers are super old an largely unmaintained

**Pull request merged**
