### PR TITLE
Improve update core functionality

### PR DESCRIPTION
**Pull request by swissspidy**
See #241.

@ocean90 I cannot really reproduce the bug you mentioned in #241, but I found some quirks that might actually fix it. Please have a look.

### CODE REVIEW

**Comment by ocean90** [comment]
@swissspidy The button gets disabled but the issue remains.
disabled

**Comment by swissspidy** [comment]
Ah, now I got it!

That's because of [these lines](https://github.com/obenland/shiny-updates/blob/c5bedc7f90494b052cc30b3bb4e7e7d5d363ffc0/src/js/shiny-updates.js#L1405-L1409) we added in #230.

Basically, the core update is taken from the queue and re-added to it as long as it's not empty. The spinner is only ever added once the update is started — which it hasn't at this point. So that's not exactly a _bug_. You'll notice that with dozens of updates, it handles one update after the other.

Theoretically we could remove that part because of [these lines](https://github.com/obenland/shiny-updates/blob/c5bedc7f90494b052cc30b3bb4e7e7d5d363ffc0/src/js/shiny-updates.js#L2069-L2072) which ensure we only ever redirect to the about page when everything is done. However, that could lead to some race conditions where a core is updated before a plugin and vice versa.

**Comment by ocean90** [comment]
> You'll notice that with dozens of updates, it handles one update after the other.

Right, but all the others get the spinner, that's the confusing part.

theme


Maybe there should be another status "Waiting…" or "In Preparation…"?

**Comment by swissspidy** [comment]
> Maybe there should be another status "Waiting…" or "In Preparation…"?

+1 for "Waiting…".

@mapk @obenland What do you think about that?

**Comment by ocean90** [comment]
Another idea: Change it to a "Remove" button to be able to remove the update from the queue. ¯\_(ツ)_/¯

**Comment by swissspidy** [comment]
See #180 and #203 for similar suggestions.

I'd think of that more as a "Cancel" button. If we go that route, I'd turn the "Update All" into the "Cancel" button (because that's the button you clicked on before) and leave the core update button as "Waiting…"

It was [previously suggested](https://github.com/obenland/shiny-updates/issues/180#issuecomment-223053583) that this workflow is currently out of scope for the plugin given the timeline, but that we might want to add it once it's in core

**Comment by obenland** [comment]
> The spinner is only ever added once the update is started — which it hasn't at this point.
@swissspidy Why is the spinner added for all plugins at once then, and not the core updates? If all of them spun, we wouldn't have to come up with a new type of message

**Comment by swissspidy** [comment]
@obenland Because the changes in #230 only affect core 🙂

For plugins it adds one to the queue, starts the update, adds the next one to the queue, and so on. This leads to the feeling that the spinner is added for all at the same time.

**Comment by obenland** [comment]
Should that be moved into `updateCore` then?

**Comment by swissspidy** [comment]
`updateCore` isn't executed until the queue is empty because of #230. Or am I missing something?

**Comment by ocean90** [comment]
As mentioned in the issue, it's inconsistent at the moment. Sometimes a core update gets a spinner, sometimes not.

**Comment by obenland** [comment]
I meant if we should move the changes from #230 into `updateCore`.

**Comment by swissspidy** [comment]
Gotcha, sorry. Yeah that would allow us to add the spinner earlier or show a "Waiting…" message (which would be more correct in theory).

**Comment by mapk** [comment]
I actually like the idea of adding a "Waiting" message to keep the user informed of what's going on. I was looking for an icon we could use to express that as well. Maybe: https://developer.wordpress.org/resource/dashicons/#clock

**Comment by obenland** [comment]
> I actually like the idea of adding a "Waiting" message

Let's open an enhancement ticket for that once this is in core.

**Pull request merged**
