### PR TITLE
Remove core patch.

### PR DESCRIPTION
**Pull request by obenland**
I think rather than removing the second bulk selector, we should make
it work with it.

@adamsilverstein, what do you think?

### CODE REVIEW

**Comment by adamsilverstein** [comment]
Thats fine. If we leave it, we need to figure out how to alert the user about the progress for the bulk action being performed. currently we are updating progress at the top of the page, and if the plugin list is long and the user is at the bottom selector they will not see the progress updates. Maybe a spinner here near the action button with a link to the top?

**Comment by adamsilverstein** [comment]
I also had one other fix in develop, but i think i can move this to the plugin js directly instead of a patch.

```
Index: src/wp-admin/js/updates.js
===================================================================
--- src/wp-admin/js/updates.js	(revision 36084)
+++ src/wp-admin/js/updates.js	(working copy)
@@ -524,6 +524,11 @@
 			e.preventDefault();
 			var $button = $( e.target );

+			// Do nothing if button disabled.
+			if ( $button.hasClass( 'button-disabled' ) ) {
+				return;
+			}
+
 			if ( wp.updates.shouldRequestFilesystemCredentials && ! wp.updates.updateLock ) {
 				wp.updates.requestFilesystemCredentials( e );
 			}

```

**Comment by obenland** [comment]
> currently we are updating progress at the top of the page, and if the plugin list is long and the user is at the bottom selector they will not see the progress updates.

http://tholman.com/elevator.js/ ;)

**Comment by obenland** [comment]
We talked about introducing another easter egg. That could be it.

**Comment by adamsilverstein** [comment]
love it, i never noticed the music :)

**Pull request merged**
