### PR TITLE
Update readme with some more information and animated gif's

### PR DESCRIPTION
**Pull request by j-falk**
Looked at some other featured plugins and tried to borrow some structure to the readme and also included 2 animated gif's so a new visitor quickly can understand the concept of what we are trying to do.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
This looks like an improvement to me. The installation reminded me that we could totally maybe convince @dd32 to automatically push this to the plugin repo nightly. If we go that route, we'd need a slightly different readme format or an additional readme (I think).

**Comment by obenland** [comment]
> The installation reminded me that we could totally maybe convince @dd32 to automatically push this to the plugin repo nightly.

That is already in place: https://wordpress.org/plugins/shiny-updates/

**Comment by obenland** [comment]
I'm not sure we need to duplicate the plugin headers the repository is looking for for GitHub's markdown version. Let's keep it concise and to the point.

The gifs might make more sense in the repo, where they can provide context for users, we probably don't need that on the GitHub side. Also keep in mind that this document is the first thing people will see when they find the repo, it should be more about getting started with contributions than anything else.

We could build a "Testing" section for people who are not interested in coding but still want to help out, around
> Also available on https://wordpress.org/plugins/shiny-updates/ which is automatically synced with the github repository.

**Comment by j-falk** [comment]
When I looked at some other feature plugins (2FA, Shortcake) they had the plugins header at the top, but I think that might be since they have the readme.md automatically generated by the readme.txt.

2FA seems to be using this tools library, https://github.com/xwp/wp-dev-lib, as a submodule which have one feature to automatically sync the readme.txt and readme.md so you don't need to maintain both files.

But I agree that they could have different purpose and shouldn't be too much work of maintaining two readme-files.

If we do that I agree that the animated gif's fits well in the screenshots tab on the .org repo. Right now they probably gets too much attention, but I think it's a good way for people to quickly understand what the purpose of shiny-updates is all about. It would help people like in this support-ticket https://wordpress.org/support/topic/0-443?replies=3.

A question, the existing github > .org sync, how does it work? Is it run daily or on every commit?

**Comment by dd32** [comment]
FWIW Here's a readme.md which will work for both WordPress.org & Github:
https://github.com/dd32/feature-plugin-testing

The only thing that doesn't really work well are images (You have to choose WordPress.org or Github style, they're completely different from eachother).

But who cares about all this, just focus on the plugin and providing patches of distinct parts of code which can be committed to core.

**Comment by j-falk** [comment]
Thanks Dion, when you say it works for both WordPress.org and Github I guess you mean the syntax right? You would still need to have two seperate files, readme.md and readme.txt, but could then probably setup a sync so you only have to maintain one of the files?

Agree that the focus should be on the actual plugin, but think a better readme could help get more people to contribute and lower some barriers, especially for people who typically don't write code.

**Comment by dd32** [comment]
> You would still need to have two seperate files, readme.md and readme.txt, but could then probably setup a sync so you only have to maintain one of the files?

No. It'll work with the .md file if it's in a syntax that WordPress.org recognises, which that file is.

**Comment by j-falk** [comment]
Ok, great. Then I might think we should apply KISS and only go for the single readme.md but try to keep it focused on getting started with contributions?

**Comment by j-falk** [comment]
What about the Travis Build Status, can that be included as it is now or should it be moved away from the title?

**Comment by obenland** [comment]
Most of this was used for [the plugin's page on the WordPress.org plugin directory](https://wordpress.org/plugins/shiny-updates/). Thank you!

**Pull request closed without merging**
