### PR TITLE
Update javascript qunit tests

### PR DESCRIPTION
**Pull request by ryelle**
Starting this PR for some discussion about what tests are needed. I've cleaned up the file a little, and added a few more "things to test" as commented-out `QUnit.test()`s – but these mostly came from reading the `shiny-updates.js` file, so I don't know if they're important things to the project.

I can add real tests to these in the next few days, but I'd appreciate some direction if this isn't what you're looking for :)

### CODE REVIEW

**Comment by swissspidy** [comment]
Both the cleanup as well as the suggested tests look good to me so far. Really appreciate it!

**Comment by obenland** [comment]
Thanks for getting this started @ryelle! I added you as a committer too so you can work directly with the repo.

In terms of direction—I'm a qunit novice so I'd be happy with any direction you'd want to take this. The one test that has really helped me in the past is `Plugins are queued when the lock is set`. I actually had it fail a couple of times during development and it saved me from introducing bugs.

When I wrote the few tests that we have, I wondered how event handlers that rely on DOM elements are tests (if at all). I took a stab at refactoring some of the install*/update*/delete* methods to avoid referencing HTML elements but didn't get very far on that. So it _felt_ like shiny updates was not very testable to me, is there anything that stands out to you that we can do to make it more testable?

**Comment by ryelle** [comment]
Testing DOM elements: I'm following [core's pattern](https://core.trac.wordpress.org/browser/trunk/tests/qunit/index.html) by including the HTML on the test index.html, and that seems to be allowing me to test the `decrementCounter` function, by mocking the admin bar & menu HTML. Currently this is failing — I'm not sure if `decrementCounter` is meant to update the screen reader text (which doesn't have the right aria attribute to be read to screen readers), or if this should use `wp.a11y.speak` instead (or if it tells the SR user some other way).

Testing the API calls: I've added sinon, also used in core, to check that the update/install/delete functions make the right ajax request.

**Comment by swissspidy** [comment]
Cool, I can have a look at `decrementCounter` later.

For now, to fix the jshint error you can add `sinon` as a global to the `.jshintrc` file.

**Comment by ryelle** [comment]
Looks like [this change to shiny-updates.js](https://github.com/obenland/shiny-updates/commit/0a168c81b5688c564d808a5216b6c2dbcc93b9fd#diff-63e316f9867ea7079d200956f14de84d) is making it impossible to adjust the `pagenow` global for testing. `pagenow` is set once when shiny-updates.js is loaded, and then can't be updated. I can add it to the fixtures to define it at the start, but then we can't change it for themes/core/etc.

I was actually hoping to merge this soon, then continue working on other tests, but since `pagenow` is undefined, the `updatePlugin` calls are failing. Any ideas? It seems like only `updatePlugin` really _needs_ the pagenow defined, so we could leave it as `plugins` for the entire test suite, but that doesn't seem like good test practice.

**Comment by obenland** [comment]
@swissspidy What do you think about reverting to referencing `pagenow` from the `window` object?
Would making it more testable be a good justification for it?

**Pull request merged**
