### PR TITLE
Make sure the re-install card cannot be empty

### LINKED ISSUE #253: "Need to re-install WordPress?" can be empty
empty

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #253

### CODE REVIEW

**Comment by swissspidy** [comment]
@obenland Assigning to you for review. The `$first_pass` check is a bit ugly, but it ensures that multiple updates could be shown in that box.

**Comment by obenland** [comment]
Looking at the diff, I'm not sure what changed logically. How can I test this, and what exactly is it supposed to fix?

**Comment by swissspidy** [comment]
@obenland This is basically a follow-up to #243, where I changed the logic from using `$update = array_pop( $core_updates );` to using a `foreach( $core_updates as $update )` loop.

In that process I forgot that the content isn't always displayed because of the `if ( isset( $update->response ) && 'latest' !== $update->response ) {` check further down.

That's why I opened this PR to only add the re-install card when there really was something to display.

**Comment by afragen** [comment]
Yeah, that was my fault 😉

**Pull request merged**
